# Usando a imagem oficial do Python
FROM python:3.11-slim

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando o código fonte para o container
COPY client.py /app/

# Comando para rodar o cliente
CMD ["python", "client.py"]
