version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  client:
    build:
      context: .
      dockerfile: client.dockerfile
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
